$axure.loadCurrentPage({
  "url":"基本信息.html",
  "generationDate":new Date(1497939799665.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2df07916a8954c999f8d32dfefce430f",
    "type":"Axure:Page",
    "name":"基本信息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7f421b4a4fd2489bb2779ad95500e0d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F6F8},
            "location":{
              "x":14,
              "y":0},
            "size":{
              "width":1366,
              "height":1040},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f1ba80cb1948a0b8b0db5072033c39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8},
                "location":{
                  "x":14,
                  "y":0},
                "size":{
                  "width":1366,
                  "height":1040},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u0.png"}},
{
          "id":"048984c816af416783cbcdc1894e4295",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE5E8ED},
            "location":{
              "x":80,
              "y":118},
            "size":{
              "width":300,
              "height":260},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f92f0d92fd8947bcb896bd688a03f4a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E8ED},
                "location":{
                  "x":80,
                  "y":118},
                "size":{
                  "width":300,
                  "height":260},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的主页/u2.png"}},
{
          "id":"5618ec1572cc4dc3809c918e67a99e8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":378},
            "size":{
              "width":300,
              "height":542},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd1def5f6793413282f439d506940f94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":378},
                "size":{
                  "width":300,
                  "height":542},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u4.png"}},
{
          "id":"9ecc11b5201f4cb989bed16846ac82bc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":428,
              "y":118},
            "size":{
              "width":876,
              "height":882},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d924da1d0dfb4d8391e4f98299d875aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":428,
                  "y":118},
                "size":{
                  "width":876,
                  "height":882},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u6.png"}},
{
          "id":"3948e400f97a48fdabe46d41a27d31fb",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":410,
              "y":177},
            "size":{
              "width":876,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的主页/u8_line.png"}},
{
          "id":"11c647b29e374dd8a4a0642b57b37591",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "location":{
              "x":447,
              "y":138},
            "size":{
              "width":130,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"922a3095a778433daab094f3daecf4b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "location":{
                  "x":447,
                  "y":138},
                "size":{
                  "width":130,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14fff4fdb6a24e6cb9e1fa9a1c45ee9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF90D0E7}},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF4AA5C7},
            "location":{
              "x":770,
              "y":945},
            "size":{
              "width":100,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF90D0E7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cb6386d4a5b4e9eab59675be0fb62b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFFFFFF,
                      "opacity":1},
                    "fill":{
                      "fillType":"solid",
                      "color":0xFF90D0E7}},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4AA5C7},
                "location":{
                  "x":770,
                  "y":945},
                "size":{
                  "width":100,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF90D0E7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u11.png",
            "mouseDown~":"images/基本信息/u11_mouseDown.png"}},
{
          "id":"39a16e629f4e484bbaee770625b1f758",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":172},
            "size":{
              "width":100,
              "height":100},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"545ae7aaafac4094b348ceaeb1615ba3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":172},
                "size":{
                  "width":100,
                  "height":100},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的主页/u11.png"}},
{
          "id":"c9ab93dedf6e43ec9616488cb3547906",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"16px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "lineSpacing":"25px",
            "location":{
              "x":165,
              "y":295},
            "size":{
              "width":130,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"658eb1387ee8404993bc39f7b1d099d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"16px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "lineSpacing":"25px",
                "location":{
                  "x":165,
                  "y":295},
                "size":{
                  "width":130,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1ab3363e46bd47299ce713590e1a0835",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"dc7a5adba0c64b62ad9a8dfb92f4bb05"},
{
          "id":"9f7735a75bef4cd197a8d353a0ac8369",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":216},
            "size":{
              "width":83,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b1a865224724fe9a665d06d0054e499",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":216},
                "size":{
                  "width":83,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2bc196b125c241dd9cd9f5d90108010b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":210},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"4ae3a3536cd048578f424d13f36d3a06",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":256},
            "size":{
              "width":83,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ab8aae9a79f457ebda4568131d861c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":256},
                "size":{
                  "width":83,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb4f9972fd854f338626915114c81a23",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":250},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"94e7bdcadffa4406abd7495b3404926d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":295},
            "size":{
              "width":106,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"39cf06dd7e8241df8cc26f4c7a73b544",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":295},
                "size":{
                  "width":106,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be92a8f4c35a49d3802a0a6b8cbc3cc5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":376},
            "size":{
              "width":83,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac1f78f10adf44e2a848b91ed1cc51c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":376},
                "size":{
                  "width":83,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96db72fc489e462eacd4ed6cdbfcca05",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":416},
            "size":{
              "width":83,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"581d416a3d1e43e492725701baa671d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":416},
                "size":{
                  "width":83,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db8c81cf5f8a48e5a5bd8419fee0ddb5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":411},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"e251be1b68d54afda4dd05db71ae1bb5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":397},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"220d3271e61348b7b8b55fb045285923",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":397},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3619ce33a96e4de7b4746b83e653b9ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":500},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de5f59a35edc45c5a90237188a1339f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":500},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bc9fbb6c1b894bc983c6c54578ad7976",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":120,
              "y":528},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d957e6393b6b4e03850869aae737d0f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":120,
                  "y":528},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 登录密码",
                      "target":{
                        "targetType":"page",
                        "url":"登录密码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增项目/u40.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"78594337b7ac45ea8a6f0a453b8eb2ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4AA5C7,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE5E8ED}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F6F8},
            "location":{
              "x":120,
              "y":425},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"590f9c473f964a3abe5cbada6073ef78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4AA5C7,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE5E8ED}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8},
                "location":{
                  "x":120,
                  "y":425},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u42_mouseOver.png",
            "mouseOver~":"images/基本信息/u56_mouseOver.png"}},
{
          "id":"0f25644c851d469bbcaed65e1f708b0b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":430},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9b16a890d6d407e90758946083abec5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":430},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u58.png"}},
{
          "id":"817bc28e06aa400fbde73cf2acd2e853",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":533},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d399b89f730943a0bfa19dbd1a2c89ef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":533},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u60.png"}},
{
          "id":"32a47806f3744b73a71d2fcbfa8b399d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":120,
              "y":455},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04de6078b7cf4662bcd25bcdbeaf77cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":120,
                  "y":455},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 链接",
                      "target":{
                        "targetType":"page",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"3111c16fc2084622935df39814b4360f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":138,
              "y":460},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"adbfd4fbb9ba447fa80008968d4e2524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":138,
                  "y":460},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/基本信息/u64.png"}},
{
          "id":"f18c0e33fd1c49e88c23d54f271b4e3d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":290},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"3a0ebf494a7e48ae9b91bd7cd0fdfae6",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":371},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"fdbed997eaae4dbea60a6f861e8d486c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":455},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a2f93ee0dba4ca0b4f2db8663d494bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":455},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fa8a772f37a43aebdf14046150e59c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":495},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83f4479d80d541e8b19f0be3fc374ac3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":495},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0f69b18e102242fa801fb2882577d7cb",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":669,
              "y":771},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"e30418ef7e4741c5892d78f7c5c404ef",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":671,
              "y":851},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"fcf930e5169c4683999df6b58196ff25",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":491},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aa9886e4f22d4b93adf38c431769d84e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":535},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a82423a85c7e455ab15bcb45e463d705",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":535},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d3930d68941474487c960c3bb8febee",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":574},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa1a26a220e04ca180a68f828933145a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":574},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"86394a92a57f46f28ca5594e8557f9e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":658},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38d97808b94c4aa3a1ba3bf42e37a4d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":658},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b9db72fb03924d0c80f421738cb47791",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":698},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4053d0dac9a14b7cb985c2dd8bdd74e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":698},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab7d61efaec64aa7afe5a6f99583bb2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":737},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c5b47925ffd4774b9ec87343693e9cd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":737},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7bf725224e054c83940d690663cd3cc2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":461,
              "y":777},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0ee1df60fa54894a544170ba42992df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":461,
                  "y":777},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9426fba308c44299b31c1efc38dff606",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":461,
              "y":817},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4ad17e7debb444cb55b7c567847b013",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":461,
                  "y":817},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1b0faeee92bf42c88e0b581bf6d9faad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":461,
              "y":856},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8031fbb4fe854dc289aea353a03a2a77",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":461,
                  "y":856},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b75511a6db3f4b8f87d28691ef749adc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":896},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55ec233682204cc48f4969e5c1ef21d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":896},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6260d2cc8ae84e00908b4381867114b4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":893},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2c4c6227d1304eec947e32ac15bc6d00",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":451},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"572b7ca2828a4e478a8831ff0f5308cf",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":527},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"7a3903bbff5e434f86a3e3afaad8f104",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":567},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"ec01e6aa089d4dcf90a1129d8a8c444f",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":651},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"e3324e59ee4843ceb5e2936bf31e6dca",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":691},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"a29264e4dfcd4cbfb7b85870e65f8aa9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":614},
            "size":{
              "width":193,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ae61c0338704d988206d09ebdce7be9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":614},
                "size":{
                  "width":193,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"618c9a28e9e74fc78b202e513e6d9995",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":607},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"2df30c520b5a467eb48dbeb0d397dc4a",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":731},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"1a9915aab0434d04b0b9dab24c2e9569",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":671,
              "y":811},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"c5a34387999847f2a22a2b4d812908a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":447,
              "y":335},
            "size":{
              "width":173,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d922d4f43b14f1580c1f722dd825698",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":447,
                  "y":335},
                "size":{
                  "width":173,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0900338d5964fc48fadca0f458f3732",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF666666,
              "opacity":1},
            "location":{
              "x":670,
              "y":330},
            "size":{
              "width":340,
              "height":30}},
          "adaptiveStyles":{
}}]}},
  "masters":{
    "dc7a5adba0c64b62ad9a8dfb92f4bb05":{
      "packageId":"dc7a5adba0c64b62ad9a8dfb92f4bb05",
      "type":"Axure:Master",
      "name":"导航（服务商）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8f928c8f2d3642f4a123a4fcf2e1dc74",
            "label":"导航",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"033eb5b1ccca4f35956e2b876d4b169f",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"8e578d2f1ba14138b7f26d5501ff4119",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE5E8ED},
                      "size":{
                        "width":1366,
                        "height":88},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"06a3a9bd14da4a758cebbd78d160eed7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE5E8ED},
                          "size":{
                            "width":1366,
                            "height":88},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u56.png"}},
{
                    "id":"54f6bd1240144a28b1d10b005d0d1add",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "location":{
                        "x":260,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9e88a6ae4f084e4ba542a07a5d53a7d3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "location":{
                            "x":260,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 我的主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"我的主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"13ada9a123b448769841166c2d697db3",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":409,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"05236a7993b149f4b678d4227fe9e050",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":409,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 全部",
                                "target":{
                                  "targetType":"page",
                                  "url":"全部.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"346dd271d2854ae6bfbe824a54d6cbf7",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":559,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4f66c34323a141bdbd8c6db36afc7f19",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":559,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"34f7c3ce8dc449e9833909929cde710f",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":80,
                        "y":28},
                      "size":{
                        "width":133,
                        "height":33}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6a48864f922d4d519e6588fc510bbe98",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":80,
                            "y":28},
                          "size":{
                            "width":133,
                            "height":33}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u64.png"}},
{
                    "id":"c7b1170bffa14ca3a2f1c21b46b6ac85",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1140,
                        "y":30},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e21870f64b1c43e08a85fa26ec828709",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1140,
                            "y":30},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 项目消息",
                                "target":{
                                  "targetType":"page",
                                  "url":"项目消息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u66.png"}},
{
                    "id":"6f70ee9bb41741d19509bb3d7d2d6037",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1217,
                        "y":25},
                      "size":{
                        "width":40,
                        "height":40},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"92d10ad966664942adeb7dfc4ba8e0e5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1217,
                            "y":25},
                          "size":{
                            "width":40,
                            "height":40},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u68.png"}},
{
                    "id":"0681f0cb99a94c4abaf0e9597bf6cf1b",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1270,
                        "y":34},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"43fd4bfaf61543ab8d5fb671a09739be",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1270,
                            "y":34},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"显示/隐藏部件",
                                "objectsToFades":[]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u70.png"}},
{
                    "id":"a4ebe3cbe94e454cb3feccb42be944e2",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":699,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0d78888c843b456dbddb9720dc0b8dc3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":699,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]}]}}},
  "objectPaths":{
    "7f421b4a4fd2489bb2779ad95500e0d3":{
      "scriptId":"u0"},
    "d6f1ba80cb1948a0b8b0db5072033c39":{
      "scriptId":"u1"},
    "048984c816af416783cbcdc1894e4295":{
      "scriptId":"u2"},
    "f92f0d92fd8947bcb896bd688a03f4a5":{
      "scriptId":"u3"},
    "5618ec1572cc4dc3809c918e67a99e8a":{
      "scriptId":"u4"},
    "dd1def5f6793413282f439d506940f94":{
      "scriptId":"u5"},
    "9ecc11b5201f4cb989bed16846ac82bc":{
      "scriptId":"u6"},
    "d924da1d0dfb4d8391e4f98299d875aa":{
      "scriptId":"u7"},
    "3948e400f97a48fdabe46d41a27d31fb":{
      "scriptId":"u8"},
    "11c647b29e374dd8a4a0642b57b37591":{
      "scriptId":"u9"},
    "922a3095a778433daab094f3daecf4b9":{
      "scriptId":"u10"},
    "14fff4fdb6a24e6cb9e1fa9a1c45ee9f":{
      "scriptId":"u11"},
    "3cb6386d4a5b4e9eab59675be0fb62b6":{
      "scriptId":"u12"},
    "39a16e629f4e484bbaee770625b1f758":{
      "scriptId":"u13"},
    "545ae7aaafac4094b348ceaeb1615ba3":{
      "scriptId":"u14"},
    "c9ab93dedf6e43ec9616488cb3547906":{
      "scriptId":"u15"},
    "658eb1387ee8404993bc39f7b1d099d8":{
      "scriptId":"u16"},
    "1ab3363e46bd47299ce713590e1a0835":{
      "scriptId":"u17",
      "8f928c8f2d3642f4a123a4fcf2e1dc74":{
        "scriptId":"u18"},
      "8e578d2f1ba14138b7f26d5501ff4119":{
        "scriptId":"u19"},
      "06a3a9bd14da4a758cebbd78d160eed7":{
        "scriptId":"u20"},
      "54f6bd1240144a28b1d10b005d0d1add":{
        "scriptId":"u21"},
      "9e88a6ae4f084e4ba542a07a5d53a7d3":{
        "scriptId":"u22"},
      "13ada9a123b448769841166c2d697db3":{
        "scriptId":"u23"},
      "05236a7993b149f4b678d4227fe9e050":{
        "scriptId":"u24"},
      "346dd271d2854ae6bfbe824a54d6cbf7":{
        "scriptId":"u25"},
      "4f66c34323a141bdbd8c6db36afc7f19":{
        "scriptId":"u26"},
      "34f7c3ce8dc449e9833909929cde710f":{
        "scriptId":"u27"},
      "6a48864f922d4d519e6588fc510bbe98":{
        "scriptId":"u28"},
      "c7b1170bffa14ca3a2f1c21b46b6ac85":{
        "scriptId":"u29"},
      "e21870f64b1c43e08a85fa26ec828709":{
        "scriptId":"u30"},
      "6f70ee9bb41741d19509bb3d7d2d6037":{
        "scriptId":"u31"},
      "92d10ad966664942adeb7dfc4ba8e0e5":{
        "scriptId":"u32"},
      "0681f0cb99a94c4abaf0e9597bf6cf1b":{
        "scriptId":"u33"},
      "43fd4bfaf61543ab8d5fb671a09739be":{
        "scriptId":"u34"},
      "a4ebe3cbe94e454cb3feccb42be944e2":{
        "scriptId":"u35"},
      "0d78888c843b456dbddb9720dc0b8dc3":{
        "scriptId":"u36"}},
    "9f7735a75bef4cd197a8d353a0ac8369":{
      "scriptId":"u37"},
    "5b1a865224724fe9a665d06d0054e499":{
      "scriptId":"u38"},
    "2bc196b125c241dd9cd9f5d90108010b":{
      "scriptId":"u39"},
    "4ae3a3536cd048578f424d13f36d3a06":{
      "scriptId":"u40"},
    "2ab8aae9a79f457ebda4568131d861c9":{
      "scriptId":"u41"},
    "bb4f9972fd854f338626915114c81a23":{
      "scriptId":"u42"},
    "94e7bdcadffa4406abd7495b3404926d":{
      "scriptId":"u43"},
    "39cf06dd7e8241df8cc26f4c7a73b544":{
      "scriptId":"u44"},
    "be92a8f4c35a49d3802a0a6b8cbc3cc5":{
      "scriptId":"u45"},
    "ac1f78f10adf44e2a848b91ed1cc51c3":{
      "scriptId":"u46"},
    "96db72fc489e462eacd4ed6cdbfcca05":{
      "scriptId":"u47"},
    "581d416a3d1e43e492725701baa671d5":{
      "scriptId":"u48"},
    "db8c81cf5f8a48e5a5bd8419fee0ddb5":{
      "scriptId":"u49"},
    "e251be1b68d54afda4dd05db71ae1bb5":{
      "scriptId":"u50"},
    "220d3271e61348b7b8b55fb045285923":{
      "scriptId":"u51"},
    "3619ce33a96e4de7b4746b83e653b9ec":{
      "scriptId":"u52"},
    "de5f59a35edc45c5a90237188a1339f7":{
      "scriptId":"u53"},
    "bc9fbb6c1b894bc983c6c54578ad7976":{
      "scriptId":"u54"},
    "d957e6393b6b4e03850869aae737d0f2":{
      "scriptId":"u55"},
    "78594337b7ac45ea8a6f0a453b8eb2ca":{
      "scriptId":"u56"},
    "590f9c473f964a3abe5cbada6073ef78":{
      "scriptId":"u57"},
    "0f25644c851d469bbcaed65e1f708b0b":{
      "scriptId":"u58"},
    "a9b16a890d6d407e90758946083abec5":{
      "scriptId":"u59"},
    "817bc28e06aa400fbde73cf2acd2e853":{
      "scriptId":"u60"},
    "d399b89f730943a0bfa19dbd1a2c89ef":{
      "scriptId":"u61"},
    "32a47806f3744b73a71d2fcbfa8b399d":{
      "scriptId":"u62"},
    "04de6078b7cf4662bcd25bcdbeaf77cd":{
      "scriptId":"u63"},
    "3111c16fc2084622935df39814b4360f":{
      "scriptId":"u64"},
    "adbfd4fbb9ba447fa80008968d4e2524":{
      "scriptId":"u65"},
    "f18c0e33fd1c49e88c23d54f271b4e3d":{
      "scriptId":"u66"},
    "3a0ebf494a7e48ae9b91bd7cd0fdfae6":{
      "scriptId":"u67"},
    "fdbed997eaae4dbea60a6f861e8d486c":{
      "scriptId":"u68"},
    "6a2f93ee0dba4ca0b4f2db8663d494bc":{
      "scriptId":"u69"},
    "5fa8a772f37a43aebdf14046150e59c2":{
      "scriptId":"u70"},
    "83f4479d80d541e8b19f0be3fc374ac3":{
      "scriptId":"u71"},
    "0f69b18e102242fa801fb2882577d7cb":{
      "scriptId":"u72"},
    "e30418ef7e4741c5892d78f7c5c404ef":{
      "scriptId":"u73"},
    "fcf930e5169c4683999df6b58196ff25":{
      "scriptId":"u74"},
    "aa9886e4f22d4b93adf38c431769d84e":{
      "scriptId":"u75"},
    "a82423a85c7e455ab15bcb45e463d705":{
      "scriptId":"u76"},
    "6d3930d68941474487c960c3bb8febee":{
      "scriptId":"u77"},
    "aa1a26a220e04ca180a68f828933145a":{
      "scriptId":"u78"},
    "86394a92a57f46f28ca5594e8557f9e2":{
      "scriptId":"u79"},
    "38d97808b94c4aa3a1ba3bf42e37a4d3":{
      "scriptId":"u80"},
    "b9db72fb03924d0c80f421738cb47791":{
      "scriptId":"u81"},
    "4053d0dac9a14b7cb985c2dd8bdd74e5":{
      "scriptId":"u82"},
    "ab7d61efaec64aa7afe5a6f99583bb2f":{
      "scriptId":"u83"},
    "3c5b47925ffd4774b9ec87343693e9cd":{
      "scriptId":"u84"},
    "7bf725224e054c83940d690663cd3cc2":{
      "scriptId":"u85"},
    "a0ee1df60fa54894a544170ba42992df":{
      "scriptId":"u86"},
    "9426fba308c44299b31c1efc38dff606":{
      "scriptId":"u87"},
    "c4ad17e7debb444cb55b7c567847b013":{
      "scriptId":"u88"},
    "1b0faeee92bf42c88e0b581bf6d9faad":{
      "scriptId":"u89"},
    "8031fbb4fe854dc289aea353a03a2a77":{
      "scriptId":"u90"},
    "b75511a6db3f4b8f87d28691ef749adc":{
      "scriptId":"u91"},
    "55ec233682204cc48f4969e5c1ef21d8":{
      "scriptId":"u92"},
    "6260d2cc8ae84e00908b4381867114b4":{
      "scriptId":"u93"},
    "2c4c6227d1304eec947e32ac15bc6d00":{
      "scriptId":"u94"},
    "572b7ca2828a4e478a8831ff0f5308cf":{
      "scriptId":"u95"},
    "7a3903bbff5e434f86a3e3afaad8f104":{
      "scriptId":"u96"},
    "ec01e6aa089d4dcf90a1129d8a8c444f":{
      "scriptId":"u97"},
    "e3324e59ee4843ceb5e2936bf31e6dca":{
      "scriptId":"u98"},
    "a29264e4dfcd4cbfb7b85870e65f8aa9":{
      "scriptId":"u99"},
    "7ae61c0338704d988206d09ebdce7be9":{
      "scriptId":"u100"},
    "618c9a28e9e74fc78b202e513e6d9995":{
      "scriptId":"u101"},
    "2df30c520b5a467eb48dbeb0d397dc4a":{
      "scriptId":"u102"},
    "1a9915aab0434d04b0b9dab24c2e9569":{
      "scriptId":"u103"},
    "c5a34387999847f2a22a2b4d812908a1":{
      "scriptId":"u104"},
    "3d922d4f43b14f1580c1f722dd825698":{
      "scriptId":"u105"},
    "a0900338d5964fc48fadca0f458f3732":{
      "scriptId":"u106"}}});