$axure.loadCurrentPage({
  "url":"已提交.html",
  "generationDate":new Date(1497939800765.09),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b99602272dfd4c82a2d6383835110cf6",
    "type":"Axure:Page",
    "name":"已提交",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9e11f95d19d34f9e8cce302abc982ed2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F6F8},
            "size":{
              "width":1366,
              "height":786},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c423c9d1f2541f483ce04439d9e50b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8},
                "size":{
                  "width":1366,
                  "height":786},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u0.png"}},
{
          "id":"8edcbfa5fd9d432b9de87f4ea1b8f98e",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"dc7a5adba0c64b62ad9a8dfb92f4bb05"},
{
          "id":"15f531acae484df99360ff3f71daaea4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":118},
            "size":{
              "width":300,
              "height":642},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a7f0619f9049b5a6d940c565539c13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":118},
                "size":{
                  "width":300,
                  "height":642},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u36.png"}},
{
          "id":"250d474e8d33433ebe50fc7d6d2935a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":151},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"887bb1031ce147ab8872603cf6c1470f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":151},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0ef54d482a149c3afe1a888cf535628",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":120,
              "y":180},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c3014cd292a481cba8c37742233e1e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":120,
                  "y":180},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u40.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"aac7af8523f249dd83c69ef1485ade60",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F6F8},
            "location":{
              "x":120,
              "y":210},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbbdd245f56e4d50a7050138fc9cabb3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8},
                "location":{
                  "x":120,
                  "y":210},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u42_mouseOver.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"56615431b42a42e4b57045163dd0b03a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0099FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":120,
              "y":240},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b15b2dad83949478a23730f0729eb05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0099FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":120,
                  "y":240},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u40.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"0af3445440da4afbbff3c4ff4a0a1c72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":118},
            "size":{
              "width":876,
              "height":142},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7f70fbd41c7413f8bc164513e384840",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":414,
                  "y":118},
                "size":{
                  "width":876,
                  "height":142},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/未提交/u32.png"}},
{
          "id":"49d458233ff74818bc2fc95194fb07ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":450,
              "y":177},
            "size":{
              "width":660,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eac0c52b06d4f4a8b7fafd12f2cc5d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":450,
                  "y":177},
                "size":{
                  "width":660,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c70e4ca033884bfb86dc0557fe02c3ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":450,
              "y":212},
            "size":{
              "width":396,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d211e0cfcab046c4bdd60d51225b1c9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":450,
                  "y":212},
                "size":{
                  "width":396,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0166ea7a18c2444bb5a08ece24e0043d",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":1110,
              "y":172.5},
            "size":{
              "width":10,
              "height":32},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/未提交/u38_line.png"}},
{
          "id":"46b2c1d4612647cda50d56d430dd46ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF6AB8DA,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":1160,
              "y":176},
            "size":{
              "width":80,
              "height":25},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF6AB8DA}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73f1df2d57ac45efba7dbedb3520dc12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF6AB8DA,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":1160,
                  "y":176},
                "size":{
                  "width":80,
                  "height":25},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF6AB8DA}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 问卷详情",
                      "target":{
                        "targetType":"page",
                        "url":"问卷详情_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/未提交/u39.png"}}]}},
  "masters":{
    "dc7a5adba0c64b62ad9a8dfb92f4bb05":{
      "packageId":"dc7a5adba0c64b62ad9a8dfb92f4bb05",
      "type":"Axure:Master",
      "name":"导航（服务商）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8f928c8f2d3642f4a123a4fcf2e1dc74",
            "label":"导航",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"033eb5b1ccca4f35956e2b876d4b169f",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"8e578d2f1ba14138b7f26d5501ff4119",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE5E8ED},
                      "size":{
                        "width":1366,
                        "height":88},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"06a3a9bd14da4a758cebbd78d160eed7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE5E8ED},
                          "size":{
                            "width":1366,
                            "height":88},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u56.png"}},
{
                    "id":"54f6bd1240144a28b1d10b005d0d1add",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "location":{
                        "x":260,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9e88a6ae4f084e4ba542a07a5d53a7d3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "location":{
                            "x":260,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 我的主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"我的主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"13ada9a123b448769841166c2d697db3",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":409,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"05236a7993b149f4b678d4227fe9e050",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":409,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 全部",
                                "target":{
                                  "targetType":"page",
                                  "url":"全部.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"346dd271d2854ae6bfbe824a54d6cbf7",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":559,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4f66c34323a141bdbd8c6db36afc7f19",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":559,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"34f7c3ce8dc449e9833909929cde710f",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":80,
                        "y":28},
                      "size":{
                        "width":133,
                        "height":33}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6a48864f922d4d519e6588fc510bbe98",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":80,
                            "y":28},
                          "size":{
                            "width":133,
                            "height":33}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u64.png"}},
{
                    "id":"c7b1170bffa14ca3a2f1c21b46b6ac85",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1140,
                        "y":30},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e21870f64b1c43e08a85fa26ec828709",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1140,
                            "y":30},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 项目消息",
                                "target":{
                                  "targetType":"page",
                                  "url":"项目消息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u66.png"}},
{
                    "id":"6f70ee9bb41741d19509bb3d7d2d6037",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1217,
                        "y":25},
                      "size":{
                        "width":40,
                        "height":40},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"92d10ad966664942adeb7dfc4ba8e0e5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1217,
                            "y":25},
                          "size":{
                            "width":40,
                            "height":40},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u68.png"}},
{
                    "id":"0681f0cb99a94c4abaf0e9597bf6cf1b",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1270,
                        "y":34},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"43fd4bfaf61543ab8d5fb671a09739be",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1270,
                            "y":34},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"显示/隐藏部件",
                                "objectsToFades":[]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u70.png"}},
{
                    "id":"a4ebe3cbe94e454cb3feccb42be944e2",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":699,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0d78888c843b456dbddb9720dc0b8dc3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":699,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]}]}}},
  "objectPaths":{
    "9e11f95d19d34f9e8cce302abc982ed2":{
      "scriptId":"u0"},
    "2c423c9d1f2541f483ce04439d9e50b4":{
      "scriptId":"u1"},
    "8edcbfa5fd9d432b9de87f4ea1b8f98e":{
      "scriptId":"u2",
      "8f928c8f2d3642f4a123a4fcf2e1dc74":{
        "scriptId":"u3"},
      "8e578d2f1ba14138b7f26d5501ff4119":{
        "scriptId":"u4"},
      "06a3a9bd14da4a758cebbd78d160eed7":{
        "scriptId":"u5"},
      "54f6bd1240144a28b1d10b005d0d1add":{
        "scriptId":"u6"},
      "9e88a6ae4f084e4ba542a07a5d53a7d3":{
        "scriptId":"u7"},
      "13ada9a123b448769841166c2d697db3":{
        "scriptId":"u8"},
      "05236a7993b149f4b678d4227fe9e050":{
        "scriptId":"u9"},
      "346dd271d2854ae6bfbe824a54d6cbf7":{
        "scriptId":"u10"},
      "4f66c34323a141bdbd8c6db36afc7f19":{
        "scriptId":"u11"},
      "34f7c3ce8dc449e9833909929cde710f":{
        "scriptId":"u12"},
      "6a48864f922d4d519e6588fc510bbe98":{
        "scriptId":"u13"},
      "c7b1170bffa14ca3a2f1c21b46b6ac85":{
        "scriptId":"u14"},
      "e21870f64b1c43e08a85fa26ec828709":{
        "scriptId":"u15"},
      "6f70ee9bb41741d19509bb3d7d2d6037":{
        "scriptId":"u16"},
      "92d10ad966664942adeb7dfc4ba8e0e5":{
        "scriptId":"u17"},
      "0681f0cb99a94c4abaf0e9597bf6cf1b":{
        "scriptId":"u18"},
      "43fd4bfaf61543ab8d5fb671a09739be":{
        "scriptId":"u19"},
      "a4ebe3cbe94e454cb3feccb42be944e2":{
        "scriptId":"u20"},
      "0d78888c843b456dbddb9720dc0b8dc3":{
        "scriptId":"u21"}},
    "15f531acae484df99360ff3f71daaea4":{
      "scriptId":"u22"},
    "e1a7f0619f9049b5a6d940c565539c13":{
      "scriptId":"u23"},
    "250d474e8d33433ebe50fc7d6d2935a2":{
      "scriptId":"u24"},
    "887bb1031ce147ab8872603cf6c1470f":{
      "scriptId":"u25"},
    "a0ef54d482a149c3afe1a888cf535628":{
      "scriptId":"u26"},
    "2c3014cd292a481cba8c37742233e1e0":{
      "scriptId":"u27"},
    "aac7af8523f249dd83c69ef1485ade60":{
      "scriptId":"u28"},
    "dbbdd245f56e4d50a7050138fc9cabb3":{
      "scriptId":"u29"},
    "56615431b42a42e4b57045163dd0b03a":{
      "scriptId":"u30"},
    "9b15b2dad83949478a23730f0729eb05":{
      "scriptId":"u31"},
    "0af3445440da4afbbff3c4ff4a0a1c72":{
      "scriptId":"u32"},
    "e7f70fbd41c7413f8bc164513e384840":{
      "scriptId":"u33"},
    "49d458233ff74818bc2fc95194fb07ae":{
      "scriptId":"u34"},
    "7eac0c52b06d4f4a8b7fafd12f2cc5d3":{
      "scriptId":"u35"},
    "c70e4ca033884bfb86dc0557fe02c3ba":{
      "scriptId":"u36"},
    "d211e0cfcab046c4bdd60d51225b1c9f":{
      "scriptId":"u37"},
    "0166ea7a18c2444bb5a08ece24e0043d":{
      "scriptId":"u38"},
    "46b2c1d4612647cda50d56d430dd46ed":{
      "scriptId":"u39"},
    "73f1df2d57ac45efba7dbedb3520dc12":{
      "scriptId":"u40"}}});