$axure.loadCurrentPage({
  "url":"登录.html",
  "generationDate":new Date(1497939723125),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"06f56c7112314b399bc339fa34c017ca",
    "type":"Axure:Page",
    "name":"登录",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"15e9806aa6e345249aeb3805a7960757",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":-6,
              "y":0},
            "size":{
              "width":1366,
              "height":768},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e82f5c4dd46d48318058d51ca8ba3c3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-6,
                  "y":0},
                "size":{
                  "width":1366,
                  "height":768},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u0.png"}},
{
          "id":"a8a9d2d1253641069d64b15cf7ef4871",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":506,
              "y":242},
            "size":{
              "width":355,
              "height":283},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "outerShadow":{
              "on":true,
              "offsetX":5,
              "offsetY":5,
              "blurRadius":5,
              "color":{
                "r":0,
                "g":0,
                "b":0,
                "a":0.349019607843137}}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b032f6c6432b43b7b25924f4e402a3d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":506,
                  "y":242},
                "size":{
                  "width":355,
                  "height":283},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "outerShadow":{
                  "on":true,
                  "offsetX":5,
                  "offsetY":5,
                  "blurRadius":5,
                  "color":{
                    "r":0,
                    "g":0,
                    "b":0,
                    "a":0.349019607843137}}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u2.png"}},
{
          "id":"17551981d4b04531a2dab3b4f31fe83a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":566,
              "y":320},
            "size":{
              "width":235,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"730b5f4bcb7b46878172857f4043924b",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":566,
              "y":366},
            "size":{
              "width":235,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"4625c9cc028e4baf80f399f36914039d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软夜黑 Regular', '微软夜黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF009DD9},
            "location":{
              "x":566,
              "y":416},
            "size":{
              "width":234,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a92e7b3846c41658b66dd6bb992f079",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软夜黑 Regular', '微软夜黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF009DD9},
                "location":{
                  "x":566,
                  "y":416},
                "size":{
                  "width":234,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u6.png"}},
{
          "id":"359634ae44824a16a7c14907515c3bcd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":573.333312988281,
              "y":325},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25be3f9551fa4b23ae899d50c72667b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":573.333312988281,
                  "y":325},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u8.png"}},
{
          "id":"6eaa06d178534fbbb74643e57bf70eb7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":573,
              "y":371},
            "size":{
              "width":20,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ea9c9045f55454baf5fcc42c92233ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":573,
                  "y":371},
                "size":{
                  "width":20,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/登录/u10.png"}},
{
          "id":"5d223b561cf749039acdb99ceaab46f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "verticalAlignment":"middle",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF009DD9,
              "opacity":1},
            "location":{
              "x":535,
              "y":274},
            "size":{
              "width":297,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d221a95c1e2d4449b1956003f4a023a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF009DD9,
                  "opacity":1},
                "location":{
                  "x":535,
                  "y":274},
                "size":{
                  "width":297,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3a781a5dd124e608e9a13292f3f91e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"40px",
            "fontWeight":"700",
            "verticalAlignment":"middle",
            "location":{
              "x":615,
              "y":172},
            "size":{
              "width":124,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e149ca8b5447425baeb57f8f147e5339",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"40px",
                "fontWeight":"700",
                "verticalAlignment":"middle",
                "location":{
                  "x":615,
                  "y":172},
                "size":{
                  "width":124,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "15e9806aa6e345249aeb3805a7960757":{
      "scriptId":"u0"},
    "e82f5c4dd46d48318058d51ca8ba3c3b":{
      "scriptId":"u1"},
    "a8a9d2d1253641069d64b15cf7ef4871":{
      "scriptId":"u2"},
    "b032f6c6432b43b7b25924f4e402a3d2":{
      "scriptId":"u3"},
    "17551981d4b04531a2dab3b4f31fe83a":{
      "scriptId":"u4"},
    "730b5f4bcb7b46878172857f4043924b":{
      "scriptId":"u5"},
    "4625c9cc028e4baf80f399f36914039d":{
      "scriptId":"u6"},
    "8a92e7b3846c41658b66dd6bb992f079":{
      "scriptId":"u7"},
    "359634ae44824a16a7c14907515c3bcd":{
      "scriptId":"u8"},
    "25be3f9551fa4b23ae899d50c72667b7":{
      "scriptId":"u9"},
    "6eaa06d178534fbbb74643e57bf70eb7":{
      "scriptId":"u10"},
    "7ea9c9045f55454baf5fcc42c92233ac":{
      "scriptId":"u11"},
    "5d223b561cf749039acdb99ceaab46f9":{
      "scriptId":"u12"},
    "d221a95c1e2d4449b1956003f4a023a8":{
      "scriptId":"u13"},
    "e3a781a5dd124e608e9a13292f3f91e4":{
      "scriptId":"u14"},
    "e149ca8b5447425baeb57f8f147e5339":{
      "scriptId":"u15"}}});