$axure.loadCurrentPage({
  "url":"问卷详情_1.html",
  "generationDate":new Date(1497939800891.18),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a567e8206c3d40d4be7af1f64895e074",
    "type":"Axure:Page",
    "name":"问卷详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"11169e9e93314ec1843fa09829b72289",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F6F8},
            "size":{
              "width":1366,
              "height":786},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"08154679d48946528c185af23434d485",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8},
                "size":{
                  "width":1366,
                  "height":786},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u0.png"}},
{
          "id":"0c14d11069e24aeab66a8db18174ff4b",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"dc7a5adba0c64b62ad9a8dfb92f4bb05"},
{
          "id":"a29e0749004143499ce5a3eea681dee2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":183,
              "y":118},
            "size":{
              "width":1000,
              "height":642},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4c286ffb42d454db12d6914bee866db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":183,
                  "y":118},
                "size":{
                  "width":1000,
                  "height":642},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/问卷详情/u22.png"}},
{
          "id":"426536f02e6d45ba8c8da9e17236cc18",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"18px",
            "horizontalAlignment":"center",
            "location":{
              "x":558,
              "y":150},
            "size":{
              "width":250,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8766ae01854c482f848c5ea076ead6a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"18px",
                "horizontalAlignment":"center",
                "location":{
                  "x":558,
                  "y":150},
                "size":{
                  "width":250,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"34a85dbff2dd4fb4b45dee9375682d42",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":450,
              "y":212},
            "size":{
              "width":396,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1e8c50774854add88169db338504fc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":450,
                  "y":212},
                "size":{
                  "width":396,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10fcf84809884591b9736cf588f527d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "lineSpacing":"30px",
            "location":{
              "x":253,
              "y":200},
            "size":{
              "width":860,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f47a1f65b3bc4d1986009e8e90078fbb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "lineSpacing":"30px",
                "location":{
                  "x":253,
                  "y":200},
                "size":{
                  "width":860,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5f1f7f07de3b4de1a51b2ba23d5ba15a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":253,
              "y":270},
            "size":{
              "width":860,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/问卷详情/u30_line.png"}},
{
          "id":"1fcf28c2d181494483f4ba4abdf1840d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":253,
              "y":296},
            "size":{
              "width":130,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4eccd6e251584d109a8a512b25604112",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":253,
                  "y":296},
                "size":{
                  "width":130,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5dc0c10acb1d473e98a3b54d19b522e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF4AA5C7},
            "location":{
              "x":640,
              "y":700},
            "size":{
              "width":85,
              "height":30},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF4AA5C7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5416cbcb85c3463897fbbd2aef8aec62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4AA5C7},
                "location":{
                  "x":640,
                  "y":700},
                "size":{
                  "width":85,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF4AA5C7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/项目详情/u83.png"}},
{
          "id":"a1af85ae2b2d49bca6a9e396e1c22b65",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":335},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b27dc33b3bdb46cb83e1140f48c1b1fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":335},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c1f343bd20204dae865d858378c4f0dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":515,
              "y":335},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87198e3cf8e54c3586e3c5e32ba8ed07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":515,
                  "y":335},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ed7ee33c10eb44db8725ed33f3ebf29c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":717,
              "y":335},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d5fe93fcbb484687ef5b40a11a87d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":717,
                  "y":335},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cdf1fcbf4e5848bb8cc5182f93c4a715",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":335},
            "size":{
              "width":60,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8891e28c07645809e02e8774ea138de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":335},
                "size":{
                  "width":60,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "dc7a5adba0c64b62ad9a8dfb92f4bb05":{
      "packageId":"dc7a5adba0c64b62ad9a8dfb92f4bb05",
      "type":"Axure:Master",
      "name":"导航（服务商）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8f928c8f2d3642f4a123a4fcf2e1dc74",
            "label":"导航",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"033eb5b1ccca4f35956e2b876d4b169f",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"8e578d2f1ba14138b7f26d5501ff4119",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE5E8ED},
                      "size":{
                        "width":1366,
                        "height":88},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"06a3a9bd14da4a758cebbd78d160eed7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE5E8ED},
                          "size":{
                            "width":1366,
                            "height":88},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u56.png"}},
{
                    "id":"54f6bd1240144a28b1d10b005d0d1add",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "location":{
                        "x":260,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9e88a6ae4f084e4ba542a07a5d53a7d3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "location":{
                            "x":260,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 我的主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"我的主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"13ada9a123b448769841166c2d697db3",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":409,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"05236a7993b149f4b678d4227fe9e050",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":409,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 全部",
                                "target":{
                                  "targetType":"page",
                                  "url":"全部.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"346dd271d2854ae6bfbe824a54d6cbf7",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":559,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4f66c34323a141bdbd8c6db36afc7f19",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":559,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"34f7c3ce8dc449e9833909929cde710f",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":80,
                        "y":28},
                      "size":{
                        "width":133,
                        "height":33}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6a48864f922d4d519e6588fc510bbe98",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":80,
                            "y":28},
                          "size":{
                            "width":133,
                            "height":33}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u64.png"}},
{
                    "id":"c7b1170bffa14ca3a2f1c21b46b6ac85",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1140,
                        "y":30},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e21870f64b1c43e08a85fa26ec828709",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1140,
                            "y":30},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 项目消息",
                                "target":{
                                  "targetType":"page",
                                  "url":"项目消息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u66.png"}},
{
                    "id":"6f70ee9bb41741d19509bb3d7d2d6037",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1217,
                        "y":25},
                      "size":{
                        "width":40,
                        "height":40},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"92d10ad966664942adeb7dfc4ba8e0e5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1217,
                            "y":25},
                          "size":{
                            "width":40,
                            "height":40},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u68.png"}},
{
                    "id":"0681f0cb99a94c4abaf0e9597bf6cf1b",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1270,
                        "y":34},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"43fd4bfaf61543ab8d5fb671a09739be",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1270,
                            "y":34},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"显示/隐藏部件",
                                "objectsToFades":[]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u70.png"}},
{
                    "id":"a4ebe3cbe94e454cb3feccb42be944e2",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":699,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0d78888c843b456dbddb9720dc0b8dc3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":699,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]}]}}},
  "objectPaths":{
    "11169e9e93314ec1843fa09829b72289":{
      "scriptId":"u0"},
    "08154679d48946528c185af23434d485":{
      "scriptId":"u1"},
    "0c14d11069e24aeab66a8db18174ff4b":{
      "scriptId":"u2",
      "8f928c8f2d3642f4a123a4fcf2e1dc74":{
        "scriptId":"u3"},
      "8e578d2f1ba14138b7f26d5501ff4119":{
        "scriptId":"u4"},
      "06a3a9bd14da4a758cebbd78d160eed7":{
        "scriptId":"u5"},
      "54f6bd1240144a28b1d10b005d0d1add":{
        "scriptId":"u6"},
      "9e88a6ae4f084e4ba542a07a5d53a7d3":{
        "scriptId":"u7"},
      "13ada9a123b448769841166c2d697db3":{
        "scriptId":"u8"},
      "05236a7993b149f4b678d4227fe9e050":{
        "scriptId":"u9"},
      "346dd271d2854ae6bfbe824a54d6cbf7":{
        "scriptId":"u10"},
      "4f66c34323a141bdbd8c6db36afc7f19":{
        "scriptId":"u11"},
      "34f7c3ce8dc449e9833909929cde710f":{
        "scriptId":"u12"},
      "6a48864f922d4d519e6588fc510bbe98":{
        "scriptId":"u13"},
      "c7b1170bffa14ca3a2f1c21b46b6ac85":{
        "scriptId":"u14"},
      "e21870f64b1c43e08a85fa26ec828709":{
        "scriptId":"u15"},
      "6f70ee9bb41741d19509bb3d7d2d6037":{
        "scriptId":"u16"},
      "92d10ad966664942adeb7dfc4ba8e0e5":{
        "scriptId":"u17"},
      "0681f0cb99a94c4abaf0e9597bf6cf1b":{
        "scriptId":"u18"},
      "43fd4bfaf61543ab8d5fb671a09739be":{
        "scriptId":"u19"},
      "a4ebe3cbe94e454cb3feccb42be944e2":{
        "scriptId":"u20"},
      "0d78888c843b456dbddb9720dc0b8dc3":{
        "scriptId":"u21"}},
    "a29e0749004143499ce5a3eea681dee2":{
      "scriptId":"u22"},
    "c4c286ffb42d454db12d6914bee866db":{
      "scriptId":"u23"},
    "426536f02e6d45ba8c8da9e17236cc18":{
      "scriptId":"u24"},
    "8766ae01854c482f848c5ea076ead6a1":{
      "scriptId":"u25"},
    "34a85dbff2dd4fb4b45dee9375682d42":{
      "scriptId":"u26"},
    "d1e8c50774854add88169db338504fc0":{
      "scriptId":"u27"},
    "10fcf84809884591b9736cf588f527d6":{
      "scriptId":"u28"},
    "f47a1f65b3bc4d1986009e8e90078fbb":{
      "scriptId":"u29"},
    "5f1f7f07de3b4de1a51b2ba23d5ba15a":{
      "scriptId":"u30"},
    "1fcf28c2d181494483f4ba4abdf1840d":{
      "scriptId":"u31"},
    "4eccd6e251584d109a8a512b25604112":{
      "scriptId":"u32"},
    "5dc0c10acb1d473e98a3b54d19b522e9":{
      "scriptId":"u33"},
    "5416cbcb85c3463897fbbd2aef8aec62":{
      "scriptId":"u34"},
    "a1af85ae2b2d49bca6a9e396e1c22b65":{
      "scriptId":"u35"},
    "b27dc33b3bdb46cb83e1140f48c1b1fa":{
      "scriptId":"u36"},
    "c1f343bd20204dae865d858378c4f0dc":{
      "scriptId":"u37"},
    "87198e3cf8e54c3586e3c5e32ba8ed07":{
      "scriptId":"u38"},
    "ed7ee33c10eb44db8725ed33f3ebf29c":{
      "scriptId":"u39"},
    "96d5fe93fcbb484687ef5b40a11a87d7":{
      "scriptId":"u40"},
    "cdf1fcbf4e5848bb8cc5182f93c4a715":{
      "scriptId":"u41"},
    "c8891e28c07645809e02e8774ea138de":{
      "scriptId":"u42"}}});