$axure.loadCurrentPage({
  "url":"报价和提案.html",
  "generationDate":new Date(1497939798541.51),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0e002e4c266f44edaa4f203c293f0bd8",
    "type":"Axure:Page",
    "name":"报价和提案",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d8e3166fb9a34b41999b2eb8302e9a92",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F6F8},
            "size":{
              "width":1366,
              "height":994},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0b4020f82fac470698012332167e6ffd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8},
                "size":{
                  "width":1366,
                  "height":994},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的主页/u0.png"}},
{
          "id":"435fe6e8d7be4c95b265a50f907e0705",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":414,
              "y":118},
            "size":{
              "width":276,
              "height":302},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda15d9a39df40daa9493a543a02aec2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":414,
                  "y":118},
                "size":{
                  "width":276,
                  "height":302},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u2.png"}},
{
          "id":"f30380eb1a944121956e92a36bb6fce1",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"dc7a5adba0c64b62ad9a8dfb92f4bb05"},
{
          "id":"0593a19c79594d7992e803c194b4df6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"15px",
            "location":{
              "x":440,
              "y":333},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecf4ac34514f4c6f9d881530d7c100d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"15px",
                "location":{
                  "x":440,
                  "y":333},
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"25be77a249f14c258ed24887499f7bcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":440,
              "y":362},
            "size":{
              "width":133,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b130588a08840d0bff97bbcb8c761e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":440,
                  "y":362},
                "size":{
                  "width":133,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e45ea3f6814c44589a680ccf0636c8d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "location":{
              "x":440,
              "y":383},
            "size":{
              "width":210,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18f8f788b78a4516a53da3ac45b6646d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "location":{
                  "x":440,
                  "y":383},
                "size":{
                  "width":210,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d8c4cf6203884bbe98d3a4262ad854cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":414,
              "y":118},
            "size":{
              "width":276,
              "height":192},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feaab775264d4a8aa4d6691bed497036",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":414,
                  "y":118},
                "size":{
                  "width":276,
                  "height":192},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u32.png"}},
{
          "id":"93e8b7fda09f4f4a9cd12ca7af47bd82",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
},
              "mouseDown":{
},
              "selected":{
}},
            "fill":{
              "fillType":"solid",
              "color":0xFF4AA5C7},
            "location":{
              "x":600,
              "y":333},
            "size":{
              "width":65,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF90D0E7},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc6f5d6cc4e74f3d9f15b06ca7b8ae83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
},
                  "mouseDown":{
},
                  "selected":{
}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFF4AA5C7},
                "location":{
                  "x":600,
                  "y":333},
                "size":{
                  "width":65,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF90D0E7},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/报价和提案/u32.png"}},
{
          "id":"3b438519ef8643d1b5847384244d3d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":118},
            "size":{
              "width":300,
              "height":762},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0605e1cfb61f49a79f6c4f6b6c77ed81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":118},
                "size":{
                  "width":300,
                  "height":762},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部/u2.png"}},
{
          "id":"e452cb7f6dc040fe82948b4b3a90d610",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":151},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"72963708c4c944169f90ee397469f451",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":151},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f058291c69da4ecba673aa3b9a9946af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
}},
            "location":{
              "x":120,
              "y":287},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a62860a0563d48be91e12ec9b751c631",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
}},
                "location":{
                  "x":120,
                  "y":287},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u40.png"}},
{
          "id":"9bdd5646a8754dc6b84390391c62c547",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":120,
              "y":316},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e69a3b39ea5a4da7ad40e6fb46591bdc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":120,
                  "y":316},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 查看项目要求",
                      "target":{
                        "targetType":"page",
                        "url":"查看项目要求.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增项目/u40.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"45cf59064eac41a0b0df54cf3314393f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0066FF,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":120,
              "y":346},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3cc6f14fd383495abaa50e0ab939ef72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0066FF,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":120,
                  "y":346},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 报价和提案",
                      "target":{
                        "targetType":"page",
                        "url":"报价和提案.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增项目/u40.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"7fac252153354771bab25fa1abc992b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":120,
              "y":376},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f1e8ee67b8b4ea3aad6697654d82e91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":120,
                  "y":376},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 接受订单",
                      "target":{
                        "targetType":"page",
                        "url":"接受订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增项目/u40.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"17000d7e93054f199ee18cce36b4dbf3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":120,
              "y":406},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"984e7b5cb13047f986b18bfe70b9e79d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":120,
                  "y":406},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 已终止",
                      "target":{
                        "targetType":"page",
                        "url":"已终止.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/新增项目/u40.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"0a0f7c079e144a01ae48d7e72314ca47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "fill":{
              "fillType":"solid",
              "color":0xFFF5F6F8},
            "location":{
              "x":120,
              "y":180},
            "size":{
              "width":200,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef65c1877122425f8e00a1a16703d070",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8},
                "location":{
                  "x":120,
                  "y":180},
                "size":{
                  "width":200,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新增项目/u42_mouseOver.png",
            "mouseOver~":"images/新增项目/u42_mouseOver.png"}},
{
          "id":"d02b8d6e5971422b963bd361b8e6abd5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF5F6F8}}},
            "location":{
              "x":170,
              "y":210},
            "size":{
              "width":150,
              "height":30},
            "borderWidth":"-1",
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c1ed53a56b9f40cc998c88075b0c9e6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF5F6F8}}},
                "location":{
                  "x":170,
                  "y":210},
                "size":{
                  "width":150,
                  "height":30},
                "borderWidth":"-1",
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/全部/u77.png",
            "mouseOver~":"images/全部/u77_mouseOver.png"}},
{
          "id":"5aa6eee062824699a8fb6bb5848a3666",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontWeight":"700",
            "location":{
              "x":120,
              "y":258},
            "size":{
              "width":80,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87cccb9258e14ec38fb5fce1ba5ac018",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontWeight":"700",
                "location":{
                  "x":120,
                  "y":258},
                "size":{
                  "width":80,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
    "dc7a5adba0c64b62ad9a8dfb92f4bb05":{
      "packageId":"dc7a5adba0c64b62ad9a8dfb92f4bb05",
      "type":"Axure:Master",
      "name":"导航（服务商）",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"8f928c8f2d3642f4a123a4fcf2e1dc74",
            "label":"导航",
            "type":"dynamicPanel",
            "styleType":"dynamicPanel",
            "visible":true,
            "style":{
              "size":{
                "width":10,
                "height":10}},
            "adaptiveStyles":{
},
            "scrollbars":"none",
            "fitToContent":true,
            "propagate":false,
            "diagrams":[{
                "id":"033eb5b1ccca4f35956e2b876d4b169f",
                "label":"状态1",
                "type":"Axure:PanelDiagram",
                "objects":[{
                    "id":"8e578d2f1ba14138b7f26d5501ff4119",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "fill":{
                        "fillType":"solid",
                        "color":0xFFE5E8ED},
                      "size":{
                        "width":1366,
                        "height":88},
                      "borderWidth":"-1",
                      "borderFill":{
                        "fillType":"solid",
                        "color":0xFFE4E4E4}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"06a3a9bd14da4a758cebbd78d160eed7",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fill":{
                            "fillType":"solid",
                            "color":0xFFE5E8ED},
                          "size":{
                            "width":1366,
                            "height":88},
                          "borderWidth":"-1",
                          "borderFill":{
                            "fillType":"solid",
                            "color":0xFFE4E4E4}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u56.png"}},
{
                    "id":"54f6bd1240144a28b1d10b005d0d1add",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "verticalAlignment":"middle",
                      "location":{
                        "x":260,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"9e88a6ae4f084e4ba542a07a5d53a7d3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "verticalAlignment":"middle",
                          "location":{
                            "x":260,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 我的主页",
                                "target":{
                                  "targetType":"page",
                                  "url":"我的主页.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"13ada9a123b448769841166c2d697db3",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":409,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"05236a7993b149f4b678d4227fe9e050",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":409,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 全部",
                                "target":{
                                  "targetType":"page",
                                  "url":"全部.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"346dd271d2854ae6bfbe824a54d6cbf7",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":559,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"4f66c34323a141bdbd8c6db36afc7f19",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":559,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}},
{
                    "id":"34f7c3ce8dc449e9833909929cde710f",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":80,
                        "y":28},
                      "size":{
                        "width":133,
                        "height":33}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"6a48864f922d4d519e6588fc510bbe98",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":80,
                            "y":28},
                          "size":{
                            "width":133,
                            "height":33}},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u64.png"}},
{
                    "id":"c7b1170bffa14ca3a2f1c21b46b6ac85",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1140,
                        "y":30},
                      "size":{
                        "width":30,
                        "height":30}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"e21870f64b1c43e08a85fa26ec828709",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1140,
                            "y":30},
                          "size":{
                            "width":30,
                            "height":30}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 项目消息",
                                "target":{
                                  "targetType":"page",
                                  "url":"项目消息.html",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u66.png"}},
{
                    "id":"6f70ee9bb41741d19509bb3d7d2d6037",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"buttonShape",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1217,
                        "y":25},
                      "size":{
                        "width":40,
                        "height":40},
                      "borderWidth":"-1"},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"92d10ad966664942adeb7dfc4ba8e0e5",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1217,
                            "y":25},
                          "size":{
                            "width":40,
                            "height":40},
                          "borderWidth":"-1"},
                        "adaptiveStyles":{
}}],
                    "images":{
                      "normal~":"images/我的主页/u68.png"}},
{
                    "id":"0681f0cb99a94c4abaf0e9597bf6cf1b",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"imageBox",
                    "styleType":"imageBox",
                    "visible":true,
                    "style":{
                      "location":{
                        "x":1270,
                        "y":34},
                      "size":{
                        "width":20,
                        "height":20}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"43fd4bfaf61543ab8d5fb671a09739be",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "location":{
                            "x":1270,
                            "y":34},
                          "size":{
                            "width":20,
                            "height":20}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"fadeWidget",
                                "description":"显示/隐藏部件",
                                "objectsToFades":[]}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"images/我的主页/u70.png"}},
{
                    "id":"a4ebe3cbe94e454cb3feccb42be944e2",
                    "label":"",
                    "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                    "type":"buttonShape",
                    "styleType":"paragraph",
                    "visible":true,
                    "style":{
                      "fontName":"'微软雅黑 Regular', '微软雅黑'",
                      "fontSize":"16px",
                      "horizontalAlignment":"center",
                      "location":{
                        "x":699,
                        "y":34},
                      "size":{
                        "width":130,
                        "height":21}},
                    "adaptiveStyles":{
},
                    "objects":[{
                        "id":"0d78888c843b456dbddb9720dc0b8dc3",
                        "label":"",
                        "isContained":true,
                        "parentDynamicPanel":"8f928c8f2d3642f4a123a4fcf2e1dc74",
                        "type":"richTextPanel",
                        "styleType":"paragraph",
                        "visible":true,
                        "style":{
                          "fontName":"'微软雅黑 Regular', '微软雅黑'",
                          "fontSize":"16px",
                          "horizontalAlignment":"center",
                          "location":{
                            "x":699,
                            "y":34},
                          "size":{
                            "width":130,
                            "height":21}},
                        "adaptiveStyles":{
}}],
                    "interactionMap":{
                      "onClick":{
                        "description":"OnClick",
                        "cases":[{
                            "description":"用例 1",
                            "isNewIfGroup":false,
                            "actions":[{
                                "action":"linkWindow",
                                "description":"在 当前窗口 打开 链接",
                                "target":{
                                  "targetType":"page",
                                  "includeVariables":true},
                                "linkType":"current"}]}]}},
                    "tabbable":true,
                    "images":{
                      "normal~":"resources/images/transparent.gif"}}]}]}]}}},
  "objectPaths":{
    "d8e3166fb9a34b41999b2eb8302e9a92":{
      "scriptId":"u0"},
    "0b4020f82fac470698012332167e6ffd":{
      "scriptId":"u1"},
    "435fe6e8d7be4c95b265a50f907e0705":{
      "scriptId":"u2"},
    "fda15d9a39df40daa9493a543a02aec2":{
      "scriptId":"u3"},
    "f30380eb1a944121956e92a36bb6fce1":{
      "scriptId":"u4",
      "8f928c8f2d3642f4a123a4fcf2e1dc74":{
        "scriptId":"u5"},
      "8e578d2f1ba14138b7f26d5501ff4119":{
        "scriptId":"u6"},
      "06a3a9bd14da4a758cebbd78d160eed7":{
        "scriptId":"u7"},
      "54f6bd1240144a28b1d10b005d0d1add":{
        "scriptId":"u8"},
      "9e88a6ae4f084e4ba542a07a5d53a7d3":{
        "scriptId":"u9"},
      "13ada9a123b448769841166c2d697db3":{
        "scriptId":"u10"},
      "05236a7993b149f4b678d4227fe9e050":{
        "scriptId":"u11"},
      "346dd271d2854ae6bfbe824a54d6cbf7":{
        "scriptId":"u12"},
      "4f66c34323a141bdbd8c6db36afc7f19":{
        "scriptId":"u13"},
      "34f7c3ce8dc449e9833909929cde710f":{
        "scriptId":"u14"},
      "6a48864f922d4d519e6588fc510bbe98":{
        "scriptId":"u15"},
      "c7b1170bffa14ca3a2f1c21b46b6ac85":{
        "scriptId":"u16"},
      "e21870f64b1c43e08a85fa26ec828709":{
        "scriptId":"u17"},
      "6f70ee9bb41741d19509bb3d7d2d6037":{
        "scriptId":"u18"},
      "92d10ad966664942adeb7dfc4ba8e0e5":{
        "scriptId":"u19"},
      "0681f0cb99a94c4abaf0e9597bf6cf1b":{
        "scriptId":"u20"},
      "43fd4bfaf61543ab8d5fb671a09739be":{
        "scriptId":"u21"},
      "a4ebe3cbe94e454cb3feccb42be944e2":{
        "scriptId":"u22"},
      "0d78888c843b456dbddb9720dc0b8dc3":{
        "scriptId":"u23"}},
    "0593a19c79594d7992e803c194b4df6d":{
      "scriptId":"u24"},
    "ecf4ac34514f4c6f9d881530d7c100d9":{
      "scriptId":"u25"},
    "25be77a249f14c258ed24887499f7bcd":{
      "scriptId":"u26"},
    "6b130588a08840d0bff97bbcb8c761e9":{
      "scriptId":"u27"},
    "e45ea3f6814c44589a680ccf0636c8d0":{
      "scriptId":"u28"},
    "18f8f788b78a4516a53da3ac45b6646d":{
      "scriptId":"u29"},
    "d8c4cf6203884bbe98d3a4262ad854cd":{
      "scriptId":"u30"},
    "feaab775264d4a8aa4d6691bed497036":{
      "scriptId":"u31"},
    "93e8b7fda09f4f4a9cd12ca7af47bd82":{
      "scriptId":"u32"},
    "bc6f5d6cc4e74f3d9f15b06ca7b8ae83":{
      "scriptId":"u33"},
    "3b438519ef8643d1b5847384244d3d26":{
      "scriptId":"u34"},
    "0605e1cfb61f49a79f6c4f6b6c77ed81":{
      "scriptId":"u35"},
    "e452cb7f6dc040fe82948b4b3a90d610":{
      "scriptId":"u36"},
    "72963708c4c944169f90ee397469f451":{
      "scriptId":"u37"},
    "f058291c69da4ecba673aa3b9a9946af":{
      "scriptId":"u38"},
    "a62860a0563d48be91e12ec9b751c631":{
      "scriptId":"u39"},
    "9bdd5646a8754dc6b84390391c62c547":{
      "scriptId":"u40"},
    "e69a3b39ea5a4da7ad40e6fb46591bdc":{
      "scriptId":"u41"},
    "45cf59064eac41a0b0df54cf3314393f":{
      "scriptId":"u42"},
    "3cc6f14fd383495abaa50e0ab939ef72":{
      "scriptId":"u43"},
    "7fac252153354771bab25fa1abc992b7":{
      "scriptId":"u44"},
    "4f1e8ee67b8b4ea3aad6697654d82e91":{
      "scriptId":"u45"},
    "17000d7e93054f199ee18cce36b4dbf3":{
      "scriptId":"u46"},
    "984e7b5cb13047f986b18bfe70b9e79d":{
      "scriptId":"u47"},
    "0a0f7c079e144a01ae48d7e72314ca47":{
      "scriptId":"u48"},
    "ef65c1877122425f8e00a1a16703d070":{
      "scriptId":"u49"},
    "d02b8d6e5971422b963bd361b8e6abd5":{
      "scriptId":"u50"},
    "c1ed53a56b9f40cc998c88075b0c9e6a":{
      "scriptId":"u51"},
    "5aa6eee062824699a8fb6bb5848a3666":{
      "scriptId":"u52"},
    "87cccb9258e14ec38fb5fce1ba5ac018":{
      "scriptId":"u53"}}});